# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_provider_config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_provider_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61i_provider_config.proto\x12\x06sivako\"K\n\x11\x41zureOpenAIConfig\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x10\n\x08\x61pi_base\x18\x02 \x01(\t\x12\x13\n\x0b\x61pi_version\x18\x03 \x01(\t\"o\n\x0cOpenAIConfig\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x19\n\x0corganization\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08\x61pi_base\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x0f\n\r_organizationB\x0b\n\t_api_base\"F\n\x0f\x41nthropicConfig\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x15\n\x08\x61pi_base\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_api_base\"\x1f\n\x0cGeminiConfig\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"H\n\x11HuggingFaceConfig\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x15\n\x08\x61pi_base\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_api_base\"#\n\x10TogetherAIConfig\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"G\n\x10OpenRouterConfig\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x10\n\x08site_url\x18\x02 \x01(\t\x12\x10\n\x08\x61pp_name\x18\x03 \x01(\t\"\"\n\x0f\x44\x65\x65pInfraConfig\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"^\n\rBedrockConfig\x12\x19\n\x11\x61ws_access_key_id\x18\x01 \x01(\t\x12\x1d\n\x15\x61ws_secret_access_key\x18\x02 \x01(\t\x12\x13\n\x0bregion_name\x18\x03 \x01(\t\"M\n\x0eVertexAIConfig\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x18\n\x10\x63redentials_path\x18\x03 \x01(\t\" \n\x0cOllamaConfig\x12\x10\n\x08\x61pi_base\x18\x01 \x01(\t\"`\n\x0fSageMakerConfig\x12\x19\n\x11\x61ws_access_key_id\x18\x01 \x01(\t\x12\x1d\n\x15\x61ws_secret_access_key\x18\x02 \x01(\t\x12\x13\n\x0bregion_name\x18\x03 \x01(\t\"\x1f\n\x0c\x43ohereConfig\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\" \n\rMistralConfig\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"\x1d\n\nGroqConfig\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_provider_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AZUREOPENAICONFIG']._serialized_start=36
  _globals['_AZUREOPENAICONFIG']._serialized_end=111
  _globals['_OPENAICONFIG']._serialized_start=113
  _globals['_OPENAICONFIG']._serialized_end=224
  _globals['_ANTHROPICCONFIG']._serialized_start=226
  _globals['_ANTHROPICCONFIG']._serialized_end=296
  _globals['_GEMINICONFIG']._serialized_start=298
  _globals['_GEMINICONFIG']._serialized_end=329
  _globals['_HUGGINGFACECONFIG']._serialized_start=331
  _globals['_HUGGINGFACECONFIG']._serialized_end=403
  _globals['_TOGETHERAICONFIG']._serialized_start=405
  _globals['_TOGETHERAICONFIG']._serialized_end=440
  _globals['_OPENROUTERCONFIG']._serialized_start=442
  _globals['_OPENROUTERCONFIG']._serialized_end=513
  _globals['_DEEPINFRACONFIG']._serialized_start=515
  _globals['_DEEPINFRACONFIG']._serialized_end=549
  _globals['_BEDROCKCONFIG']._serialized_start=551
  _globals['_BEDROCKCONFIG']._serialized_end=645
  _globals['_VERTEXAICONFIG']._serialized_start=647
  _globals['_VERTEXAICONFIG']._serialized_end=724
  _globals['_OLLAMACONFIG']._serialized_start=726
  _globals['_OLLAMACONFIG']._serialized_end=758
  _globals['_SAGEMAKERCONFIG']._serialized_start=760
  _globals['_SAGEMAKERCONFIG']._serialized_end=856
  _globals['_COHERECONFIG']._serialized_start=858
  _globals['_COHERECONFIG']._serialized_end=889
  _globals['_MISTRALCONFIG']._serialized_start=891
  _globals['_MISTRALCONFIG']._serialized_end=923
  _globals['_GROQCONFIG']._serialized_start=925
  _globals['_GROQCONFIG']._serialized_end=954
# @@protoc_insertion_point(module_scope)
