# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding_model_provider.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding_model_provider.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ai_provider_config_pb2 as ai__provider__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x65mbedding_model_provider.proto\x12\x06sivako\x1a\x18\x61i_provider_config.proto\"\xc4\x02\n\x1c\x45mbeddingModelProviderConfig\x12\x30\n\x08provider\x18\x01 \x01(\x0e\x32\x1e.sivako.EmbeddingModelProvider\x12\x16\n\x0emax_concurrent\x18\x02 \x01(\x05\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x1a\n\x12\x63ost_per_1M_tokens\x18\x04 \x01(\x02\x12\x38\n\x13\x61zure_openai_config\x18\x05 \x01(\x0b\x32\x19.sivako.AzureOpenAIConfigH\x00\x12-\n\ropenai_config\x18\x06 \x01(\x0b\x32\x14.sivako.OpenAIConfigH\x00\x12\x37\n\x12huggingface_config\x18\x07 \x01(\x0b\x32\x19.sivako.HuggingFaceConfigH\x00\x42\x08\n\x06\x63onfig*\xbc\x01\n\x16\x45mbeddingModelProvider\x12(\n$EMBEDDING_MODEL_PROVIDER_UNSPECIFIED\x10\x00\x12)\n%EMBEDDING_MODEL_PROVIDER_AZURE_OPENAI\x10\x01\x12#\n\x1f\x45MBEDDING_MODEL_PROVIDER_OPENAI\x10\x02\x12(\n$EMBEDDING_MODEL_PROVIDER_HUGGINGFACE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_model_provider_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGMODELPROVIDER']._serialized_start=396
  _globals['_EMBEDDINGMODELPROVIDER']._serialized_end=584
  _globals['_EMBEDDINGMODELPROVIDERCONFIG']._serialized_start=69
  _globals['_EMBEDDINGMODELPROVIDERCONFIG']._serialized_end=393
# @@protoc_insertion_point(module_scope)
