# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlogging.proto\x12\x06sivako\"N\n\tCostEntry\x12\x1e\n\x04type\x18\x01 \x01(\x0e\x32\x10.sivako.CostType\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04\x63ost\x18\x03 \x01(\x02\"A\n\x07\x43ostLog\x12\"\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x11.sivako.CostEntry\x12\x12\n\ntotal_cost\x18\x02 \x01(\x02\"N\n\x08LogEntry\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x04 \x01(\t*i\n\x08\x43ostType\x12\x19\n\x15\x43OST_TYPE_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x43OST_TYPE_LM\x10\x01\x12\x17\n\x13\x43OST_TYPE_RETRIEVER\x10\x02\x12\x17\n\x13\x43OST_TYPE_EMBEDDING\x10\x03\x42\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_COSTTYPE']._serialized_start=252
  _globals['_COSTTYPE']._serialized_end=357
  _globals['_COSTENTRY']._serialized_start=25
  _globals['_COSTENTRY']._serialized_end=103
  _globals['_COSTLOG']._serialized_start=105
  _globals['_COSTLOG']._serialized_end=170
  _globals['_LOGENTRY']._serialized_start=172
  _globals['_LOGENTRY']._serialized_end=250
# @@protoc_insertion_point(module_scope)
