# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: longmemeval.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'longmemeval.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11longmemeval.proto\x12\x0blongmemeval\"T\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x17\n\nhas_answer\x18\x03 \x01(\x08H\x00\x88\x01\x01\x42\r\n\x0b_has_answer\"9\n\x0b\x43hatSession\x12*\n\x08messages\x18\x01 \x03(\x0b\x32\x18.longmemeval.ChatMessage\"\xfd\x01\n\x0fLongMemEvalItem\x12\x13\n\x0bquestion_id\x18\x01 \x01(\t\x12\x15\n\rquestion_type\x18\x02 \x01(\t\x12\x10\n\x08question\x18\x03 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x04 \x01(\t\x12\x15\n\rquestion_date\x18\x05 \x01(\t\x12\x16\n\x0ehaystack_dates\x18\x06 \x03(\t\x12\x1c\n\x14haystack_session_ids\x18\x07 \x03(\t\x12\x33\n\x11haystack_sessions\x18\x08 \x03(\x0b\x32\x18.longmemeval.ChatSession\x12\x1a\n\x12\x61nswer_session_ids\x18\t \x03(\t\"A\n\x12LongMemEvalDataset\x12+\n\x05items\x18\x01 \x03(\x0b\x32\x1c.longmemeval.LongMemEvalItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'longmemeval_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=34
  _globals['_CHATMESSAGE']._serialized_end=118
  _globals['_CHATSESSION']._serialized_start=120
  _globals['_CHATSESSION']._serialized_end=177
  _globals['_LONGMEMEVALITEM']._serialized_start=180
  _globals['_LONGMEMEVALITEM']._serialized_end=433
  _globals['_LONGMEMEVALDATASET']._serialized_start=435
  _globals['_LONGMEMEVALDATASET']._serialized_end=500
# @@protoc_insertion_point(module_scope)
