# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transform_retrieval_output.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'transform_retrieval_output.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n transform_retrieval_output.proto\x12\x06sivako\"\xfa\x01\n\x1eTransformRetrievalOutputConfig\x12\x19\n\x11summary_json_path\x18\x01 \x01(\t\x12\x1c\n\x14questions_jsonl_path\x18\x02 \x01(\t\x12\x18\n\x10output_json_path\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x61taset_name\x18\x04 \x01(\t\x12\x1a\n\x12retrieval_strategy\x18\x05 \x01(\t\x12\x0c\n\x04topk\x18\x06 \x01(\x05\x12#\n\x1bstructured_notes_jsonl_path\x18\x07 \x01(\t\x12 \n\x18segment_notes_jsonl_path\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transform_retrieval_output_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSFORMRETRIEVALOUTPUTCONFIG']._serialized_start=45
  _globals['_TRANSFORMRETRIEVALOUTPUTCONFIG']._serialized_end=295
# @@protoc_insertion_point(module_scope)
