# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: turn_encoding_strategy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'turn_encoding_strategy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cturn_encoding_strategy.proto\x12\x06sivako*\xa1\x01\n\x12TurnEncodeStrategy\x12$\n TURN_ENCODE_STRATEGY_UNSPECIFIED\x10\x00\x12*\n&TURN_ENCODE_STRATEGY_TURN_CONTENT_ONLY\x10\x01\x12\x39\n5TURN_ENCODE_STRATEGY_TURN_CONTENT_WITH_META_AND_FACTS\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'turn_encoding_strategy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TURNENCODESTRATEGY']._serialized_start=41
  _globals['_TURNENCODESTRATEGY']._serialized_end=202
# @@protoc_insertion_point(module_scope)
